apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oyins-test
  namespace: argocd
spec:
  destination:
    namespace: test-1
    server: https://kubernetes.default.svc
  source:
    repoURL: hhttps://github.com/oyinlola101/hostspace-internship.git
    path: new/helm/nginx
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
